name: Goldenboomers.com
favicon: null
layout_spectrum: 0.2810771542135626
typography_spectrum: 0.1545819602906704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5639973601792008
  lightness: 0.9303314611315727
  saturation: 0.04753648000769317
  rhythmicContrast: 0.7957020713947713
purpose: []
